version: '3'

services:
    keycloak:
        image: quay.io/keycloak/keycloak:17.0.1
        environment:
            KC_DB: postgres
            KC_DB_URL_HOST: host.docker.internal
            KC_DB_URL_DATABASE: keycloak_postgres
            KC_DB_USERNAME: root
            KC_DB_PASSWORD: root
            KC_DB_SCHEMA: public
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
            KC_HOSTNAME: localhost
            KC_METRICS_ENABLED: "true"
            KC_HTTPS_PORT: 8099
        ports:
            - 8099:8099
        volumes:
            - ./keystore.jks:/opt/keycloak/conf/server.keystore
        extra_hosts:
            - "host.docker.internal:172.17.0.1"
        command:
            - "start --auto-build"