version: '3'
services:
  postgres:
    image: "postgres:11"
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
